### PR TITLE
%selinux_modules_{,un}install: don't ignore load_policy errors

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by bachradsusi** [comment]
Would you please consider to add some references or description of the problem this patch should fix?

**Comment by bachradsusi** [comment]
Preferably directly to the commit message

**Comment by praiskup** [comment]
Added
```
Fixes `true && false || true` problem;  aka the whole shell
statement (and thus scriptlet) succeeds no matter whether
'selinuxenabled' or 'load_policy' failed.  While want to accept
non-zero value returned by `selinuxenabled`, we certainly don't
want to hide `load_policy` failure.

Originally the `|| true` was added in 8dd7ee2,
to fix rhbz#1665643 -- which was a valid user scenario where the
package is installed in environment where SELinux is disabled
(selinuxenabled returns 1).  Using `if` is better, since it only
allows non-zero value of `selinuxenabled` tool, and any
`load_policy` failure fill be again fatal.
```

**Comment by praiskup** [comment]
Per Fedora docs, scriptlets should never exit with nonzero exit status.
https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/

**Pull request closed without merging**
